name: flutkit
description: Open source flutter widgets
version: 0.0.2
author: Marko Majamaki
homepage: https://github.com/MarkoMajamaki/FlutKit

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: