name: flutkit_demo
description: Demo and testing app for flutkit
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutkit:
    path: ../flutkit

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^4.1.3

flutter:
  uses-material-design: true