name: flutkit_demo
description: Demo and testing app for flutkit
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
ersion: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutkit:
    path: ../flutkit
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true